name: Build Multi-Platform Releases

permissions:
  contents: write
  pull-requests: write

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
    
    - name: Build Windows executable
      run: |
        pyinstaller HwYtVidGrabber.spec
    
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-exe
        path: dist/HwYtVidGrabber.exe

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
    
    - name: Build macOS app
      run: |
        pyinstaller HwYtVidGrabber.spec
        # Use ditto to properly preserve extended attributes and app bundle structure
        cd dist && ditto -c -k --sequesterRsrc --keepParent HwYtVidGrabber.app HwYtVidGrabber-macOS.zip
    
    - name: Upload macOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-app
        path: dist/HwYtVidGrabber-macOS.zip

  build-linux-packages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev python3-pip build-essential fakeroot devscripts dh-python
        sudo apt-get install -y qt6-base-dev qt6-tools-dev libqt6gui6 libqt6widgets6 libgl1-mesa-dev
        sudo apt-get install -y rpm alien
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
    
    - name: Build Linux executable
      run: |
        pyinstaller HwYtVidGrabber.spec
    
    - name: Create DEB package structure
      run: |
        mkdir -p hwytvidgrabber/DEBIAN
        mkdir -p hwytvidgrabber/usr/bin
        mkdir -p hwytvidgrabber/usr/share/applications
        mkdir -p hwytvidgrabber/usr/share/pixmaps
        
        # Copy executable
        cp dist/HwYtVidGrabber hwytvidgrabber/usr/bin/
        chmod +x hwytvidgrabber/usr/bin/HwYtVidGrabber
        
        # Copy icon (create a dummy one if it doesn't exist)
        if [ -f icon.png ]; then
          cp icon.png hwytvidgrabber/usr/share/pixmaps/hwytvidgrabber.png
        else
          # Try to install imagemagick and create placeholder, or skip gracefully
          sudo apt-get install -y imagemagick || echo "Skipping placeholder icon"
          convert -size 64x64 xc:blue hwytvidgrabber/usr/share/pixmaps/hwytvidgrabber.png 2>/dev/null || echo "No icon available"
        fi
        
        # Create control file
        cat > hwytvidgrabber/DEBIAN/control << EOF
        Package: hwytvidgrabber
        Version: 1.0.0
        Section: utils
        Priority: optional
        Architecture: amd64
        Maintainer: MalikHw47 <help.malicorporation@gmail.com>
        Description: HwYtVidGrabber - YouTube Video Downloader
         A PyQt6-based YouTube video downloader application built by MalikHw47.
         Features a modern GUI for downloading videos from YouTube and other platforms.
        Depends: python3, python3-pyqt6
        EOF
        
        # Create desktop entry
        cat > hwytvidgrabber/usr/share/applications/hwytvidgrabber.desktop << EOF
        [Desktop Entry]
        Name=HwYtVidGrabber
        Comment=YouTube Video Downloader by MalikHw47
        Exec=/usr/bin/HwYtVidGrabber
        Icon=hwytvidgrabber
        Terminal=false
        Type=Application
        Categories=AudioVideo;Network;Qt;
        EOF
    
    - name: Build DEB package
      run: |
        dpkg-deb --build hwytvidgrabber
        mv hwytvidgrabber.deb HwYtVidGrabber.deb
    
    - name: Create Linux binary zip
      run: |
        mkdir -p linux-binary
        cp dist/HwYtVidGrabber linux-binary/
        chmod +x linux-binary/HwYtVidGrabber
        
        # Create a README for the binary
        cat > linux-binary/README.txt << EOF
        HwYtVidGrabber - Linux Binary
        =============================
        
        This is a standalone binary for Linux systems.
        
        To run:
        1. Make sure the binary is executable: chmod +x HwYtVidGrabber
        2. Run it: ./HwYtVidGrabber
        
        Requirements:
        - Python 3.11+ (should be pre-installed on most modern Linux distributions)
        - Qt6 libraries (install with your package manager if needed)
        
        For Ubuntu/Debian: sudo apt install python3-pyqt6
        For Fedora: sudo dnf install python3-qt6
        For Arch: sudo pacman -S python-pyqt6
        
        Created by MalikHw47
        EOF
        
        # Create the zip file
        cd linux-binary
        zip -r ../hwytvidgrabber-linux-binary.zip *
    
    - name: Create Arch-like package structure
      run: |
        mkdir -p arch-build/pkg/usr/bin arch-build/pkg/usr/share/{applications,pixmaps}
        
        cp dist/HwYtVidGrabber arch-build/pkg/usr/bin/
        chmod +x arch-build/pkg/usr/bin/HwYtVidGrabber
        
        # Copy icon if it exists
        if [ -f icon.png ]; then
          cp icon.png arch-build/pkg/usr/share/pixmaps/hwytvidgrabber.png
        fi
        
        cat > arch-build/pkg/usr/share/applications/hwytvidgrabber.desktop << 'EOF'
        [Desktop Entry]
        Name=HwYtVidGrabber
        Comment=YouTube Video Downloader by MalikHw47
        Exec=/usr/bin/HwYtVidGrabber
        Icon=hwytvidgrabber
        Terminal=false
        Type=Application
        Categories=AudioVideo;Network;Qt;
        EOF
        
        # Create Arch-like package (not a real pacman package)
        cd arch-build/pkg
        tar -czf ../../HwYtVidGrabber-archlike.tar.gz *
    
    - name: Upload Linux packages artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-packages
        path: |
          HwYtVidGrabber.deb
          hwytvidgrabber-linux-binary.zip
          HwYtVidGrabber-archlike.tar.gz

  create-release:
    needs: [build-windows, build-macos, build-linux-packages]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          windows-exe/HwYtVidGrabber.exe
          macos-app/HwYtVidGrabber-macOS.zip
          linux-packages/HwYtVidGrabber.deb
          linux-packages/hwytvidgrabber-linux-binary.zip
          linux-packages/HwYtVidGrabber-archlike.tar.gz
        draft: false
        prerelease: false
        body: |
          # HwYtVidGrabber Release
          
          Created by MalikHw47
          
          ## Downloads:
          - **Windows**: HwYtVidGrabber.exe
          - **macOS**: HwYtVidGrabber-macOS.zip (extract and run the .app)
          - **Ubuntu/Debian**: HwYtVidGrabber.deb (install with `sudo dpkg -i HwYtVidGrabber.deb`)
          - **Linux Binary**: hwytvidgrabber-linux-binary.zip (extract and run `./HwYtVidGrabber`)
          - **Arch Linux (manual install)**: Extract to `/usr/` or run directly. Not a pacman package.
          
          ## Features:
          - YouTube video downloading
          - Modern PyQt6 interface
          - Cross-platform support
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}