name: Build Multi-Platform Releases

permissions:
  contents: write
  pull-requests: write

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
    
    - name: Build Windows executable
      run: |
        pyinstaller --windowed --onefile --icon=icon.ico --add-data="icon.png;." --add-data="icon.ico;." HwYtVidGrabber.py
    
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-exe
        path: dist/HwYtVidGrabber.exe

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
    
    - name: Build macOS application
      run: |
        pyinstaller --windowed --onefile --icon=icon.ico --add-data="icon.png:." --add-data="icon.ico:." HwYtVidGrabber.py
        # Create proper .app bundle
        mkdir -p HwYtVidGrabber.app/Contents/MacOS
        mkdir -p HwYtVidGrabber.app/Contents/Resources
        
        # Move executable
        mv dist/HwYtVidGrabber HwYtVidGrabber.app/Contents/MacOS/
        
        # Copy icon
        cp icon.png HwYtVidGrabber.app/Contents/Resources/icon.png
        
        # Create Info.plist
        cat > HwYtVidGrabber.app/Contents/Info.plist << 'EOF'
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleExecutable</key>
            <string>HwYtVidGrabber</string>
            <key>CFBundleIconFile</key>
            <string>icon.png</string>
            <key>CFBundleIdentifier</key>
            <string>com.malikhw47.hwytvid-grabber</string>
            <key>CFBundleName</key>
            <string>HwYtVidGrabber</string>
            <key>CFBundlePackageType</key>
            <string>APPL</string>
            <key>CFBundleShortVersionString</key>
            <string>1.3</string>
            <key>CFBundleVersion</key>
            <string>1.3</string>
            <key>LSMinimumSystemVersion</key>
            <string>10.15</string>
            <key>NSHighResolutionCapable</key>
            <true/>
        </dict>
        </plist>
        EOF
    
    - name: Upload macOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-app
        path: HwYtVidGrabber.app

  build-linux-packages:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install system dependencies and packaging tools
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev python3-pip build-essential
        # Install Qt6 dependencies
        sudo apt-get install -y qt6-base-dev qt6-tools-dev libqt6gui6 libqt6widgets6 libqt6core6
        sudo apt-get install -y qt6-qpa-plugins libqt6dbus6 libqt6network6 libqt6svg6
        # Install packaging tools
        sudo apt-get install -y debhelper dh-python devscripts fakeroot
        sudo apt-get install -y alien rpm2cpio cpio
        # Install AppImage tools
        sudo apt-get install -y zsync desktop-file-utils file
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
    
    - name: Build base application
      run: |
        pyinstaller --onefile --windowed --icon=icon.ico --add-data="icon.png:." --add-data="icon.ico:." HwYtVidGrabber.py
        mkdir -p build-assets
        cp dist/HwYtVidGrabber build-assets/
        chmod +x build-assets/HwYtVidGrabber
    
    # Build .deb package for Debian/Ubuntu
    - name: Create DEB package structure
      run: |
        mkdir -p deb-package/DEBIAN
        mkdir -p deb-package/usr/bin
        mkdir -p deb-package/usr/share/applications
        mkdir -p deb-package/usr/share/pixmaps
        mkdir -p deb-package/usr/share/doc/hwytvid-grabber
        
        # Copy executable
        cp build-assets/HwYtVidGrabber deb-package/usr/bin/hwytvid-grabber
        
        # Copy icon
        cp icon.png deb-package/usr/share/pixmaps/hwytvid-grabber.png
        
        # Create desktop file
        cat > deb-package/usr/share/applications/hwytvid-grabber.desktop << 'EOF'
        [Desktop Entry]
        Name=HwYtVidGrabber
        Comment=YouTube Video Downloader
        Exec=hwytvid-grabber
        Icon=hwytvid-grabber
        Terminal=false
        Type=Application
        Categories=AudioVideo;Network;
        StartupWMClass=HwYtVidGrabber
        EOF
        
        # Create control file
        cat > deb-package/DEBIAN/control << 'EOF'
        Package: hwytvid-grabber
        Version: 1.3
        Section: video
        Priority: optional
        Architecture: amd64
        Depends: libqt6core6, libqt6gui6, libqt6widgets6, python3, ffmpeg
        Maintainer: help.malicorporation@gmail.com
        Description: YouTube Video Downloader
         A modern PyQt6-based YouTube video downloader with support for
         multiple formats and resolutions up to 4K.
         .
         Features include:
          - YouTube video downloading with yt-dlp
          - Modern PyQt6 interface
          - Multiple format support (MP4, MP3, muted MP4)
          - Resolution selection up to 4K
          - Dark mode support
        Homepage: https://github.com/MalikHw47/HwYtVidGrabber
        EOF
        
        # Create copyright file
        cat > deb-package/usr/share/doc/hwytvid-grabber/copyright << 'EOF'
        Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/
        Upstream-Name: HwYtVidGrabber
        Source: https://github.com/MalikHw47/HwYtVidGrabber

        Files: *
        Copyright: 2024 MalikHw47
        License: MIT
        EOF
        
        # Create changelog
        cat > deb-package/usr/share/doc/hwytvid-grabber/changelog << 'EOF'
        hwytvid-grabber (1.3) unstable; urgency=medium

          * Release version 1.3
          * Modern PyQt6 interface
          * Multiple format support
          * Cross-platform compatibility

         -- help.malicorporation@gmail.com  $(date -R)
        EOF
        
        gzip deb-package/usr/share/doc/hwytvid-grabber/changelog
        
        # Build DEB package
        dpkg-deb --build deb-package HwYtVidGrabber.deb
    
    # Build Arch Linux package
    - name: Create Arch Linux package
      run: |
        mkdir -p arch-package/pkg/usr/bin
        mkdir -p arch-package/pkg/usr/share/applications
        mkdir -p arch-package/pkg/usr/share/pixmaps
        
        # Copy files
        cp build-assets/HwYtVidGrabber arch-package/pkg/usr/bin/hwytvid-grabber
        cp deb-package/usr/share/applications/hwytvid-grabber.desktop arch-package/pkg/usr/share/applications/
        cp icon.png arch-package/pkg/usr/share/pixmaps/hwytvid-grabber.png
        
        # Create .PKGINFO
        cat > arch-package/pkg/.PKGINFO << 'EOF'
        pkgname = hwytvid-grabber
        pkgbase = hwytvid-grabber
        pkgver = 1.3-1
        pkgdesc = YouTube Video Downloader with PyQt6 interface
        url = https://github.com/MalikHw47/HwYtVidGrabber
        arch = x86_64
        license = MIT
        depend = python
        depend = qt6-base
        depend = ffmpeg
        depend = python-pyqt6
        EOF
        
        # Create package archive
        cd arch-package/pkg
        tar -czf ../../HwYtVidGrabber.pkg.tar.gz .PKGINFO usr/
    
    # Build AppImage (without FUSE requirement)
    - name: Create AppImage
      run: |
        # Download appimagetool-x86_64.AppImage
        wget -q https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x appimagetool-x86_64.AppImage
        
        # Create AppDir structure
        mkdir -p AppDir/usr/bin
        mkdir -p AppDir/usr/share/applications
        mkdir -p AppDir/usr/share/icons/hicolor/256x256/apps
        
        # Copy files
        cp build-assets/HwYtVidGrabber AppDir/usr/bin/
        cp deb-package/usr/share/applications/hwytvid-grabber.desktop AppDir/
        cp icon.png AppDir/usr/share/icons/hicolor/256x256/apps/hwytvid-grabber.png
        cp icon.png AppDir/hwytvid-grabber.png
        
        # Create AppRun
        cat > AppDir/AppRun << 'EOF'
        #!/bin/bash
        HERE="$(dirname "$(readlink -f "${0}")")"
        export PATH="${HERE}/usr/bin:${PATH}"
        export LD_LIBRARY_PATH="${HERE}/usr/lib:${LD_LIBRARY_PATH}"
        exec "${HERE}/usr/bin/HwYtVidGrabber" "$@"
        EOF
        chmod +x AppDir/AppRun
        
        # Modify desktop file for AppImage
        sed -i 's/Exec=hwytvid-grabber/Exec=HwYtVidGrabber/' AppDir/hwytvid-grabber.desktop
        
        # Build AppImage without FUSE
        ARCH=x86_64 ./appimagetool-x86_64.AppImage --appimage-extract-and-run AppDir HwYtVidGrabber.AppImage
    
    - name: Upload DEB package
      uses: actions/upload-artifact@v4
      with:
        name: linux-deb
        path: HwYtVidGrabber.deb
    
    - name: Upload Arch package
      uses: actions/upload-artifact@v4
      with:
        name: linux-arch
        path: HwYtVidGrabber.pkg.tar.gz
    
    - name: Upload AppImage
      uses: actions/upload-artifact@v4
      with:
        name: linux-appimage
        path: HwYtVidGrabber.AppImage

  create-release:
    needs: [build-windows, build-macos, build-linux-packages]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          windows-exe/HwYtVidGrabber.exe
          macos-app/HwYtVidGrabber.app
          linux-deb/HwYtVidGrabber.deb
          linux-arch/HwYtVidGrabber.pkg.tar.gz
          linux-appimage/HwYtVidGrabber.AppImage
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
