name: Build Self-Contained Multi-Platform Releases

permissions:
  contents: write
  pull-requests: write

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
    
    - name: Build fully bundled Windows executable
      run: |
        pyinstaller --windowed --onefile --icon=icon.ico --add-data="icon.png;." --add-data="icon.ico;." --collect-submodules PyQt6.QtCore --collect-submodules PyQt6.QtGui --collect-submodules PyQt6.QtWidgets --hidden-import=PyQt6.sip --collect-all yt_dlp --noconsole --name=HwYtVidGrabber HwYtVidGrabber.py
    
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-exe
        path: dist/HwYtVidGrabber.exe

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
    
    - name: Build fully bundled macOS application
      run: |
        pyinstaller --windowed --onefile --icon=icon.ico \
        --add-data="icon.png:." --add-data="icon.ico:." \
        --collect-submodules PyQt6.QtCore \
        --collect-submodules PyQt6.QtGui \
        --collect-submodules PyQt6.QtWidgets \
        --hidden-import=PyQt6.sip \
        --collect-all yt_dlp \
        --name=HwYtVidGrabber \
        HwYtVidGrabber.py
        
        # Create proper .app bundle
        mkdir -p HwYtVidGrabber.app/Contents/MacOS
        mkdir -p HwYtVidGrabber.app/Contents/Resources
        
        # Move executable
        mv dist/HwYtVidGrabber HwYtVidGrabber.app/Contents/MacOS/
        chmod +x HwYtVidGrabber.app/Contents/MacOS/HwYtVidGrabber
        
        # Copy icon
        cp icon.png HwYtVidGrabber.app/Contents/Resources/icon.png
        
        # Create Info.plist
        cat > HwYtVidGrabber.app/Contents/Info.plist << 'EOF'
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleExecutable</key>
            <string>HwYtVidGrabber</string>
            <key>CFBundleIconFile</key>
            <string>icon.png</string>
            <key>CFBundleIdentifier</key>
            <string>com.malikhw47.hwytvid-grabber</string>
            <key>CFBundleName</key>
            <string>HwYtVidGrabber</string>
            <key>CFBundlePackageType</key>
            <string>APPL</string>
            <key>CFBundleShortVersionString</key>
            <string>1.3</string>
            <key>CFBundleVersion</key>
            <string>1.3</string>
            <key>LSMinimumSystemVersion</key>
            <string>10.15</string>
            <key>NSHighResolutionCapable</key>
            <true/>
        </dict>
        </plist>
        EOF
    
    - name: Create DMG
      run: |
        # Create a temporary directory for the DMG contents
        mkdir -p dmg-contents
        
        # Copy the .app bundle to the DMG contents
        cp -R HwYtVidGrabber.app dmg-contents/
        
        # Create Applications symlink for easy installation
        ln -s /Applications dmg-contents/Applications
        
        # Create the DMG using hdiutil
        hdiutil create -volname "HwYtVidGrabber" \
                       -srcfolder dmg-contents \
                       -ov \
                       -format UDZO \
                       -imagekey zlib-level=9 \
                       HwYtVidGrabber.dmg
        
        # Verify the DMG was created
        ls -la HwYtVidGrabber.dmg
    
    - name: Upload macOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-dmg
        path: HwYtVidGrabber.dmg

  build-linux-appimage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install system dependencies and Qt6
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev python3-pip build-essential
        # Install Qt6 from apt with all plugins and dev tools
        sudo apt-get install -y pyqt6-dev pyqt6-dev-tools python3-pyqt6
        sudo apt-get install -y qt6-base-dev qt6-tools-dev qt6-qpa-plugins
        sudo apt-get install -y libqt6gui6 libqt6widgets6 libqt6core6 libqt6dbus6 libqt6network6 libqt6svg6
        # Install xcb and platform libraries
        sudo apt-get install -y libxcb1 libxcb-xinerama0 libxcb-cursor0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-shape0 libxcb-sync1 libxcb-xfixes0 libxcb-xkb1
        # Install packaging tools
        sudo apt-get install -y debhelper dh-python devscripts fakeroot alien rpm2cpio cpio
        sudo apt-get install -y zsync desktop-file-utils file patchelf
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller PyQt6 PyQt6-Qt6 yt-dlp requests
        pip install -r requirements.txt
    
    - name: Build fully bundled Linux AppImage
      run: |
        # Build with PyInstaller
        pyinstaller --onefile --windowed --icon=icon.ico \
        --add-data="icon.png:." --add-data="icon.ico:." \
        --collect-submodules PyQt6.QtCore \
        --collect-submodules PyQt6.QtGui \
        --collect-submodules PyQt6.QtWidgets \
        --hidden-import=PyQt6.sip \
        --collect-all yt_dlp \
        --name=HwYtVidGrabber \
        HwYtVidGrabber.py
        
        # Download appimagetool
        wget -q https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x appimagetool-x86_64.AppImage
        
        # Create AppDir structure
        mkdir -p AppDir/usr/bin
        mkdir -p AppDir/usr/lib
        mkdir -p AppDir/usr/plugins/platforms
        mkdir -p AppDir/usr/plugins/platformthemes
        mkdir -p AppDir/usr/plugins/xcbglintegrations
        mkdir -p AppDir/usr/share/applications
        mkdir -p AppDir/usr/share/icons/hicolor/256x256/apps
        
        # Copy the bundled executable
        cp dist/HwYtVidGrabber AppDir/usr/bin/
        
        # Find and copy ALL Qt6 libraries that the executable depends on
        echo "Copying Qt6 libraries..."
        ldd dist/HwYtVidGrabber | grep -E "(libQt6|libqt6)" | awk '{print $3}' | while read lib; do
            if [ -f "$lib" ]; then
                echo "Copying Qt6 lib: $lib"
                cp "$lib" AppDir/usr/lib/
            fi
        done
        
        # Copy additional Qt6 libraries from system
        for lib in /usr/lib/x86_64-linux-gnu/libQt6*.so*; do
            if [ -f "$lib" ]; then
                echo "Copying system Qt6 lib: $lib"
                cp "$lib" AppDir/usr/lib/ 2>/dev/null || true
            fi
        done
        
        # Copy xcb and related libraries
        echo "Copying XCB libraries..."
        for lib in /usr/lib/x86_64-linux-gnu/libxcb*.so*; do
            if [ -f "$lib" ]; then
                echo "Copying XCB lib: $lib"
                cp "$lib" AppDir/usr/lib/ 2>/dev/null || true
            fi
        done
        
        # Copy Qt6 platform plugins (THE IMPORTANT PART!)
        echo "Copying Qt6 platform plugins..."
        QT6_PLUGINS_PATH=$(python3 -c "import PyQt6.QtCore; import os; print(os.path.join(os.path.dirname(PyQt6.QtCore.__file__), 'Qt6', 'plugins'))" 2>/dev/null || echo "")
        
        # Try multiple possible Qt6 plugin locations
        for plugin_base in "$QT6_PLUGINS_PATH" "/usr/lib/x86_64-linux-gnu/qt6/plugins" "/usr/lib/qt6/plugins"; do
            if [ -d "$plugin_base/platforms" ]; then
                echo "Found Qt6 plugins at: $plugin_base"
                cp -r "$plugin_base/platforms/"* AppDir/usr/plugins/platforms/ 2>/dev/null || true
                cp -r "$plugin_base/platformthemes/"* AppDir/usr/plugins/platformthemes/ 2>/dev/null || true
                cp -r "$plugin_base/xcbglintegrations/"* AppDir/usr/plugins/xcbglintegrations/ 2>/dev/null || true
                break
            fi
        done
        
        # Ensure we have the xcb plugin
        if [ ! -f "AppDir/usr/plugins/platforms/libqxcb.so" ]; then
            echo "ERROR: xcb plugin not found! Searching everywhere..."
            find /usr -name "libqxcb.so" 2>/dev/null | head -1 | while read xcb_plugin; do
                if [ -f "$xcb_plugin" ]; then
                    echo "Found xcb plugin at: $xcb_plugin"
                    cp "$xcb_plugin" AppDir/usr/plugins/platforms/
                fi
            done
        fi
        
        # List what we got
        echo "Platform plugins in AppImage:"
        ls -la AppDir/usr/plugins/platforms/
        
        # Create desktop file
        cat > AppDir/usr/share/applications/hwytvid-grabber.desktop << 'EOF'
        [Desktop Entry]
        Name=HwYtVidGrabber
        Comment=YouTube Video Downloader
        Exec=HwYtVidGrabber
        Icon=hwytvid-grabber
        Terminal=false
        Type=Application
        Categories=AudioVideo;Network;
        StartupWMClass=HwYtVidGrabber
        EOF
        
        # Copy desktop file to root
        cp AppDir/usr/share/applications/hwytvid-grabber.desktop AppDir/
        
        # Copy icons
        cp icon.png AppDir/usr/share/icons/hicolor/256x256/apps/hwytvid-grabber.png
        cp icon.png AppDir/hwytvid-grabber.png
        
        # Create AppRun with proper Qt6 environment
        cat > AppDir/AppRun << 'EOF'
        #!/bin/bash
        HERE="$(dirname "$(readlink -f "${0}")")"
        
        # Set up paths
        export PATH="${HERE}/usr/bin:${PATH}"
        export LD_LIBRARY_PATH="${HERE}/usr/lib:${LD_LIBRARY_PATH}"
        
        # Qt6 plugin paths
        export QT_PLUGIN_PATH="${HERE}/usr/plugins"
        export QT_QPA_PLATFORM_PLUGIN_PATH="${HERE}/usr/plugins/platforms"
        
        # Force xcb platform
        export QT_QPA_PLATFORM=xcb
        
        # Debug info
        echo "Qt6 Platform plugins available:"
        ls "${HERE}/usr/plugins/platforms/" 2>/dev/null || echo "No platform plugins found!"
        
        # Run the app
        exec "${HERE}/usr/bin/HwYtVidGrabber" "$@"
        EOF
        chmod +x AppDir/AppRun
        
        # Build AppImage
        ARCH=x86_64 ./appimagetool-x86_64.AppImage --appimage-extract-and-run AppDir HwYtVidGrabber.AppImage
    
    - name: Upload AppImage
      uses: actions/upload-artifact@v4
      with:
        name: linux-appimage
        path: HwYtVidGrabber.AppImage

  build-linux-packages:
    needs: [build-linux-appimage]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Download AppImage
      uses: actions/download-artifact@v4
      with:
        name: linux-appimage
    
    - name: Extract AppImage and create packages
      run: |
        chmod +x HwYtVidGrabber.AppImage
        
        # Extract AppImage contents
        ./HwYtVidGrabber.AppImage --appimage-extract
        
        # Build .deb package WITHOUT Qt6 libraries (use system ones)
        mkdir -p deb-package/DEBIAN
        mkdir -p deb-package/opt/hwytvid-grabber
        mkdir -p deb-package/usr/bin
        mkdir -p deb-package/usr/share/applications
        mkdir -p deb-package/usr/share/pixmaps
        mkdir -p deb-package/usr/share/doc/hwytvid-grabber
        
        # Copy ONLY the Python executable and yt-dlp data (no Qt6 libs)
        mkdir -p deb-package/opt/hwytvid-grabber/usr/bin
        cp squashfs-root/usr/bin/HwYtVidGrabber deb-package/opt/hwytvid-grabber/usr/bin/
        
        # Copy only non-Qt6 libraries if any
        if [ -d "squashfs-root/usr/lib" ]; then
            mkdir -p deb-package/opt/hwytvid-grabber/usr/lib
            for lib in squashfs-root/usr/lib/*; do
                if [[ ! $(basename "$lib") == libQt6* ]] && [[ ! $(basename "$lib") == libxcb* ]]; then
                    cp "$lib" deb-package/opt/hwytvid-grabber/usr/lib/ 2>/dev/null || true
                fi
            done
        fi
        
        # Copy icons and desktop files (not Qt6 plugins)
        cp squashfs-root/hwytvid-grabber.desktop deb-package/opt/hwytvid-grabber/
        cp squashfs-root/hwytvid-grabber.png deb-package/opt/hwytvid-grabber/
        
        # Create wrapper script that uses system Qt6
        cat > deb-package/usr/bin/hwytvid-grabber << 'EOF'
        #!/bin/bash
        # Use system Qt6 libraries and plugins
        export QT_QPA_PLATFORM=xcb
        export LD_LIBRARY_PATH="/opt/hwytvid-grabber/usr/lib:${LD_LIBRARY_PATH}"
        exec /opt/hwytvid-grabber/usr/bin/HwYtVidGrabber "$@"
        EOF
        chmod +x deb-package/usr/bin/hwytvid-grabber
        
        # Copy desktop file and icon
        cp deb-package/opt/hwytvid-grabber/hwytvid-grabber.desktop deb-package/usr/share/applications/
        cp deb-package/opt/hwytvid-grabber/hwytvid-grabber.png deb-package/usr/share/pixmaps/
        
        # Fix desktop file Exec path
        sed -i 's/Exec=HwYtVidGrabber/Exec=hwytvid-grabber/' deb-package/usr/share/applications/hwytvid-grabber.desktop
        
        # Create control file with Qt6 dependencies from apt
        cat > deb-package/DEBIAN/control << 'EOF'
        Package: hwytvid-grabber
        Version: 1.3
        Section: video
        Priority: optional
        Architecture: amd64
        Depends: fuse, libc6, python3-pyqt6, qt6-qpa-plugins, libqt6gui6, libqt6widgets6, libqt6core6, libxcb1, libxcb-xinerama0, libxcb-cursor0
        Maintainer: help.malicorporation@gmail.com
        Description: YouTube Video Downloader with system Qt6 libraries
         A modern PyQt6-based YouTube video downloader that uses system Qt6 libraries.
         This package installs Qt6 dependencies from official repositories.
         .
         Features include:
          - YouTube video downloading with yt-dlp
          - Modern PyQt6 interface (uses system libraries)
          - Multiple format support (MP4, MP3, muted MP4)
          - Resolution selection up to 4K
          - Dark mode support
          - Uses system Qt6 packages to avoid conflicts
        Homepage: https://github.com/MalikHw47/HwYtVidGrabber
        EOF
        
        # Create copyright file
        cat > deb-package/usr/share/doc/hwytvid-grabber/copyright << 'EOF'
        Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/
        Upstream-Name: HwYtVidGrabber
        Source: https://github.com/MalikHw47/HwYtVidGrabber

        Files: *
        Copyright: 2024 MalikHw47
        License: MIT
        EOF
        
        # Create changelog
        cat > deb-package/usr/share/doc/hwytvid-grabber/changelog << 'EOF'
        hwytvid-grabber (1.3) unstable; urgency=medium

          * Release version 1.3 - System Qt6 libraries
          * Uses system Qt6 packages to avoid conflicts
          * Automatically installs Qt6 dependencies from apt
          * Only bundles Python app, not Qt6 libraries

         -- help.malicorporation@gmail.com  $(date -R)
        EOF
        
        gzip deb-package/usr/share/doc/hwytvid-grabber/changelog
        
        # Build DEB package
        dpkg-deb --build deb-package HwYtVidGrabber.deb
        
        # Build Arch Linux package WITHOUT Qt6 libraries (use system ones)
        mkdir -p arch-package/pkg/opt/hwytvid-grabber
        mkdir -p arch-package/pkg/usr/bin
        mkdir -p arch-package/pkg/usr/share/applications
        mkdir -p arch-package/pkg/usr/share/pixmaps
        
        # Copy only the Python executable (no Qt6 libs)
        mkdir -p arch-package/pkg/opt/hwytvid-grabber/usr/bin
        cp squashfs-root/usr/bin/HwYtVidGrabber arch-package/pkg/opt/hwytvid-grabber/usr/bin/
        
        # Copy only non-Qt6 libraries
        if [ -d "squashfs-root/usr/lib" ]; then
            mkdir -p arch-package/pkg/opt/hwytvid-grabber/usr/lib
            for lib in squashfs-root/usr/lib/*; do
                if [[ ! $(basename "$lib") == libQt6* ]] && [[ ! $(basename "$lib") == libxcb* ]]; then
                    cp "$lib" arch-package/pkg/opt/hwytvid-grabber/usr/lib/ 2>/dev/null || true
                fi
            done
        fi
        
        # Copy icons and desktop files
        cp squashfs-root/hwytvid-grabber.desktop arch-package/pkg/opt/hwytvid-grabber/
        cp squashfs-root/hwytvid-grabber.png arch-package/pkg/opt/hwytvid-grabber/
        
        # Create wrapper script that uses system Qt6
        cat > arch-package/pkg/usr/bin/hwytvid-grabber << 'EOF'
        #!/bin/bash
        # Use system Qt6 libraries and plugins
        export QT_QPA_PLATFORM=xcb
        export LD_LIBRARY_PATH="/opt/hwytvid-grabber/usr/lib:${LD_LIBRARY_PATH}"
        exec /opt/hwytvid-grabber/usr/bin/HwYtVidGrabber "$@"
        EOF
        chmod +x arch-package/pkg/usr/bin/hwytvid-grabber
        
        # Copy desktop file and icon
        cp arch-package/pkg/opt/hwytvid-grabber/hwytvid-grabber.desktop arch-package/pkg/usr/share/applications/
        cp arch-package/pkg/opt/hwytvid-grabber/hwytvid-grabber.png arch-package/pkg/usr/share/pixmaps/
        
        # Create .PKGINFO with Qt6 dependencies
        cat > arch-package/pkg/.PKGINFO << 'EOF'
        pkgname = hwytvid-grabber
        pkgbase = hwytvid-grabber
        pkgver = 1.3-1
        pkgdesc = YouTube Video Downloader using system Qt6 libraries
        url = https://github.com/MalikHw47/HwYtVidGrabber
        arch = x86_64
        license = MIT
        depend = fuse
        depend = glibc
        depend = python-pyqt6
        depend = qt6-base
        EOF
        
        # Create package archive
        cd arch-package/pkg
        tar -czf ../../HwYtVidGrabber.pkg.tar.gz .PKGINFO opt/ usr/
    
    - name: Upload DEB package
      uses: actions/upload-artifact@v4
      with:
        name: linux-deb
        path: HwYtVidGrabber.deb
    
    - name: Upload Arch package
      uses: actions/upload-artifact@v4
      with:
        name: linux-arch
        path: HwYtVidGrabber.pkg.tar.gz

  create-release:
    needs: [build-windows, build-macos, build-linux-appimage, build-linux-packages]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          windows-exe/HwYtVidGrabber.exe
          macos-dmg/HwYtVidGrabber.dmg
          linux-deb/HwYtVidGrabber.deb
          linux-arch/HwYtVidGrabber.pkg.tar.gz
          linux-appimage/HwYtVidGrabber.AppImage
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
